export {default as SocialMedia} from './SocialMedia/SocialMedia'
export {default as DotNavigation} from './DotNavigation/DotNavigation'
export {default as Navbar} from './Navbar/Navbar'
export {default as ContactForm} from './ContactForm/ContactForm'
export {default as SkillsList} from './SkillsList/SkillsList'
export {default as TestimonialsSlider} from './TestimonialsSlider/TestimonialsSlider'
export {default as WorksFilters} from './WorksFilters/WorksFilters'
export {default as PortfolioCard} from './PortfolioCard/PortfolioCard'