import { Navbar } from "@/components";

export const metadata = {
	title: "Next.js",
	description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body>
				<Navbar/>
				<main>{children}</main>
			</body>
		</html>
	);
}
